# Site settings
title: "Shane Weaver"
description: "Senior Software Engineer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Shane Weaver"
resume_title:                   "Senior Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "shanebweaver@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "253-355-4790"
resume_contact_address:         "Seattle, WA"

resume_header_contact_info:     "Seattle, WA • 253-355-4790 • shanebweaver@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<ul><li>Award-winning Windows application developer with a focus on client application architecture and accessible UX.</li><li>Contributor to open-source projects such as the Windows Community Toolkit.</li><li>Over 15 years of industry experience in software design, analysis, and full stack development.</li><li>Over 8 years of experience working inside Microsoft and with the Windows developer community.</li><li>Experienced in a variety of roles covering software engineering, partner engagement, product development, development operations, and developer support.</li></ul>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
# resume_section_education:       true
resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/shweaver-MSFT"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/shanebweaver"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://www.shanebweaver.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
